"""The owner-editable `.env` subset.

Two properties carry real risk and are pinned hardest: the allow-list must be an ALLOW-list (an
unknown key is refused, never written), and the file must be rewritten IN PLACE — `.env` is a
single-FILE bind mount, so replacing it hands the host a new inode while the container keeps reading
the old one, and the change silently does not apply.
"""
import os

import pytest

from geodeploy.services import envfile


@pytest.fixture
def env(tmp_path):
    p = tmp_path / ".env"
    p.write_text(
        "# generated by the installer\n"
        "GEODEPLOY_SECRET_KEY=super-secret\n"
        "POSTGIS_PASSWORD=hunter2\n"
        "PMTILES_TILE_MEMORY_LIMIT=1GB\n",
        encoding="utf-8")
    return str(p)


def test_only_allow_listed_keys_are_exposed(env):
    keys = {v["key"] for v in envfile.list_editable(env)}
    assert "PMTILES_TILE_MEMORY_LIMIT" in keys
    # The two that would cause data loss or fight the wizard must not be reachable at all.
    assert "GEODEPLOY_SECRET_KEY" not in keys
    assert "POSTGIS_PASSWORD" not in keys


def test_writing_an_unknown_key_is_refused(env):
    with pytest.raises(ValueError):
        envfile.write({"GEODEPLOY_SECRET_KEY": "new"}, env)
    with pytest.raises(ValueError):
        envfile.write({"TOTALLY_MADE_UP": "x"}, env)
    # ...and the refusal must not have written anything on the way out.
    assert "GEODEPLOY_SECRET_KEY=super-secret" in open(env).read()


def test_secrets_survive_a_write(env):
    """The rewrite touches every line, so the lines it must NOT change are the ones to check."""
    envfile.write({"PMTILES_TILE_THREADS": "4"}, env)
    body = open(env).read()
    assert "GEODEPLOY_SECRET_KEY=super-secret" in body
    assert "POSTGIS_PASSWORD=hunter2" in body


def test_write_preserves_the_inode(env):
    """THE bind-mount invariant. If this fails, the container keeps reading a file the host no longer
    has, and every change appears to apply while doing nothing."""
    before = os.stat(env).st_ino
    envfile.write({"PMTILES_TILE_MEMORY_LIMIT": "512MB"}, env)
    assert os.stat(env).st_ino == before


def test_existing_value_is_updated_not_duplicated(env):
    envfile.write({"PMTILES_TILE_MEMORY_LIMIT": "512MB"}, env)
    body = open(env).read()
    assert body.count("PMTILES_TILE_MEMORY_LIMIT=") == 1
    assert "512MB" in body


def test_new_key_is_appended(env):
    envfile.write({"PMTILES_MAXZOOM": "9"}, env)
    assert "PMTILES_MAXZOOM=9" in open(env).read()


def test_empty_value_removes_the_line(env):
    """Reset-to-default must REMOVE the override, not write an empty string that overrides the
    default with nothing."""
    envfile.write({"PMTILES_TILE_MEMORY_LIMIT": ""}, env)
    body = open(env).read()
    assert "PMTILES_TILE_MEMORY_LIMIT" not in body


def test_values_that_would_corrupt_the_file_are_refused(env):
    for bad in ('a"b', "a'b", "a\nB=c"):
        with pytest.raises(ValueError):
            envfile.write({"PMTILES_MAXZOOM": bad}, env)


def test_bool_validation(env):
    envfile.write({"GEODEPLOY_ENABLE_TERMINAL": "true"}, env)
    with pytest.raises(ValueError):
        envfile.write({"GEODEPLOY_ENABLE_TERMINAL": "yes-please"}, env)


def test_write_reports_the_services_needing_recreation(env):
    """Docker reads .env at container CREATE, so the caller has to know what to recreate."""
    assert envfile.write({"GEODEPLOY_ENABLE_TERMINAL": "true"}, env) == ["geodeploy-api"]
    assert envfile.write({"PMTILES_MAXZOOM": "9"}, env) == ["celery"]


def test_missing_file_is_not_an_error(tmp_path):
    p = str(tmp_path / "absent.env")
    assert envfile.list_editable(p)          # defaults, no values
    envfile.write({"PMTILES_MAXZOOM": "8"}, p)
    assert "PMTILES_MAXZOOM=8" in open(p).read()


# ── demo-only variables ─────────────────────────────────────────────────────────────────────

def test_demo_settings_are_invisible_on_a_normal_install(env):
    """A production owner must not even SEE sandbox settings, let alone a switch that arms an
    hourly wipe."""
    keys = {v["key"] for v in envfile.list_editable(env)}
    assert "GEODEPLOY_DEMO_SNAPSHOT" not in keys
    assert "GEODEPLOY_DEMO_MAX_UPLOAD_MB" not in keys


def test_demo_settings_are_refused_on_a_normal_install(env):
    """The UI omitting them is presentation. THIS is the gate — a hand-crafted request must not be
    able to configure a sandbox on a production instance. (They are now absent from EDITABLE
    outright, so this is the allow-list refusing an unknown key.)"""
    with pytest.raises(ValueError):
        envfile.write({"GEODEPLOY_DEMO_SNAPSHOT": "some-backup"}, env)


def test_demo_settings_are_invisible_even_on_a_demo(env):
    """They used to appear once the instance WAS a demo. Removed: a demo is configured by whoever has
    shell access, and splitting that across two places made `.env` disagree with the dashboard —
    hand-typed values sat under a header claiming the dashboard had written them."""
    from geodeploy.config import get_settings
    s = get_settings()
    before = s.geodeploy_demo_mode
    s.geodeploy_demo_mode = True
    try:
        keys = {v["key"] for v in envfile.list_editable(env)}
        assert "GEODEPLOY_DEMO_SNAPSHOT" not in keys
        assert "GEODEPLOY_DEMO_MAX_UPLOAD_MB" not in keys
        with pytest.raises(ValueError):
            envfile.write({"GEODEPLOY_DEMO_SNAPSHOT": "seed-2026-08-01"}, env)
    finally:
        s.geodeploy_demo_mode = before


def test_the_arming_flag_is_never_editable(env):
    """GEODEPLOY_DEMO_MODE must not be writable through this API on ANY instance, demo or not — it
    is the one setting whose cost is a deliberate edit to .env."""
    from geodeploy.config import get_settings
    s = get_settings()
    before = s.geodeploy_demo_mode
    for state in (False, True):
        s.geodeploy_demo_mode = state
        try:
            with pytest.raises(ValueError):
                envfile.write({"GEODEPLOY_DEMO_MODE": "true"}, env)
        finally:
            s.geodeploy_demo_mode = before
